services:
  api:
    build: .
    command: node dist/src/main.js
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped

  worker:
    build: .
    command: node dist/src/worker/worker.js
    env_file:
      - .env
    restart: unless-stopped