export const TransactionType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;

export const TransactionCategory = {
  FOOD: 'FOOD',
  TRANSPORTATION: 'TRANSPORTATION',
  BILLS: 'BILLS',
  SHOPPING: 'SHOPPING',
  ENTERTAINMENT: 'ENTERTAINMENT',
  HEALTHCARE: 'HEALTHCARE',
  EDUCATION: 'EDUCATION',
  TRAVEL: 'TRAVEL',
  HOUSING: 'HOUSING',
  PERSONAL_CARE: 'PERSONAL_CARE',
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  GROCERIES: 'GROCERIES',
  GIFTS_DONATIONS: 'GIFTS_DONATIONS',
  INSURANCE: 'INSURANCE',
  SALARY: 'SALARY',
  BUSINESS: 'BUSINESS',
  FREELANCE: 'FREELANCE',
  INVESTMENT: 'INVESTMENT',
  ALLOWANCE: 'ALLOWANCE',
  GIFT: 'GIFT',
  BONUS: 'BONUS',
  OTHER: 'OTHER',
} as const;

export const WalletType = {
  CASH: 'CASH',
  BANK: 'BANK',
  E_WALLET: 'E_WALLET',
  CREDIT_CARD: 'CREDIT_CARD',
  OTHER: 'OTHER',
} as const;
