name: Backend CI/CD

on:
  pull_request:
    branches:
      - dev
      - main

    types:
      - opened
      - reopened
  push:
    branches:
      - dev
      - main

  workflow_dispatch:

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read
  packages: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
  
  security:
    if: github.base_ref == 'main' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/security.yml

  build:
    needs:
      - security
      - lint
      - unit-tests

    if: >
      always() &&
      needs.lint.result == 'success' &&
      needs.unit-tests.result == 'success' &&
      (needs.security.result == 'success' || needs.security.result == 'skipped')

    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    needs:
      - build

    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      needs.build.result == 'success'

    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  notify:
    needs:
      - security
      - lint
      - unit-tests
      - build
      - publish

    if: always()

    uses: ./.github/workflows/notify.yml

    with:
      pipeline_name: Backend CI/CD
      status: ${{ contains(needs.*.result, 'failure') && 'failure' || contains(needs.*.result, 'cancelled') && 'cancelled' || 'success' }}

    secrets: inherit
