name: Deploy

on:
  workflow_call:
    secrets:
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate SSH Private Key
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          if [ -z "$SSH_PRIVATE_KEY" ]; then
            echo "ERROR: SSH_PRIVATE_KEY is empty"
            exit 1
          fi

          FIRST_LINE=$(printf '%s\n' "$SSH_PRIVATE_KEY" | head -n 1)
          LAST_LINE=$(printf '%s\n' "$SSH_PRIVATE_KEY" | tail -n 1)

          if [ "$FIRST_LINE" != "-----BEGIN OPENSSH PRIVATE KEY-----" ]; then
            echo "ERROR: Invalid private key header"
            exit 1
          fi

          if [ "$LAST_LINE" != "-----END OPENSSH PRIVATE KEY-----" ]; then
            echo "ERROR: Invalid private key footer"
            exit 1
          fi

          echo "SSH_PRIVATE_KEY exists and has the correct OpenSSH format"

      - name: Copy Docker Compose & Script to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker/docker-compose.yml,scripts/deploy.sh"
          target: "/home/${{ secrets.SSH_USER }}"

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x /home/${{ secrets.SSH_USER }}/scripts/deploy.sh
            DEPLOY_DIR=/home/${{ secrets.SSH_USER }}/docker \
              /home/${{ secrets.SSH_USER }}/scripts/deploy.sh